### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by MabudAlam** [dungngminh/adjusted_video_player#1]
Hello, I'm currently working on creating a social media clone, and I'm exploring options for implementing inline feed videos. I'm wondering if this particular plugin would be suitable for addressing this aspect of the project.

**Comment by dungngminh** [comment]
Hi there, thanks for your first opened issue. [adjusted_video_player](https://github.com/dungngminh/adjusted_video_player) is a copy of [video_player](https://pub.dev/packages/video_player) but fixed an [issue](https://github.com/flutter/flutter/issues/91241) related to HDR videos on iOS, but I don't recommend to use it for some complicated case. There are many better options for video player, you can choose [better_player](https://pub.dev/packages/better_player) or [chewie](https://pub.dev/packages/chewie). Hope you can find your own option. Thanks and have a nice day in coding 💪
